Profile Command
codesupport/old-discord-bot pull request #18
Opened 2019-10-22 18:11 UTC by LamboCreeper

This command allows users to view profile information of CodeSupport users.

This command does not have the functionality to set profile information (like the previous bot version) as I believe this will:
- act as an incentive for users to sign up to the website
- allow us to deliver a better experience for inputting data (e.g. a dropdown of countries).

I am happy to discuss this functionality removal in Discord (feel free to @mention me).

2019-10-22 19:21 UTC, saramaebee reviewed
Why is `const waitForProfileCreation` synchronous? is this not the exact use case of asynchronous programming?

2019-10-22 20:13 UTC, saramaebee requested changes
```
embed.setDescription(`${userProfile.bio ? userProfile.bio : "Not Defined"}`);
```
 and similar lines can be condensed to 
```embed.setDescription(`${userProfile.bio | "Not Defined"}`);```

2019-10-26 12:30 UTC, jacobgasser approved these changes

2019-10-26 12:44 UTC, jacobgasser approved these changes

2019-10-26 12:52 UTC, jacobgasser approved these changes

2019-10-28 11:24 UTC, saramaebee approved these changes

2019-10-28 11:24 UTC, merged