Feature/message update and delete logs
codesupport/old-discord-bot pull request #21
Opened 2019-10-26 22:17 UTC by LamboCreeper

Added logging for when a user updates or deletes a message. I feel like there could be a better way to write the actual event handler, rather than having to do something like:
```js
client.on("messageDelete", (message) => {
    events.messageDelete.run(message);
});
```
every time you want to add a new event... Suggestions welcome.

2019-10-27 18:17 UTC, jacobgasser requested changes

2019-10-27 18:17 UTC, jacobgasser commented on events/messageDelete.js
> +	embed.setDescription(`Author: ${message.author}\nChannel: ${message.channel}`);
This won't show who actually deleted the message, just the author.

2019-10-27 18:35 UTC, jacobgasser commented
There are other ways to setup the event handler but I think this way is the best because of how explicit it is. Other ways would not be so evident.

2019-10-28 11:27 UTC, saramaebee commented on events/messageDelete.js
> +	embed.setDescription(`Author: ${message.author}\nChannel: ${message.channel}`);
It is possible to access the executor by way of `GuildAuditLogsEntry.executor`, feel free to make the change

2019-10-31 21:20 UTC, LamboCreeper commented on events/messageDelete.js
> +	embed.setDescription(`Author: ${message.author}\nChannel: ${message.channel}`);
I can't seem to figure this out. If one of you would like to combat it that would be great. We don't have this feature currently, so I'm not too bothered about it not being in MVP.

2019-10-31 21:48 UTC, jacobgasser requested changes

2019-10-31 21:48 UTC, jacobgasser commented on events/messageUpdate.js
> +		embed.addField("New Message", newMessage.content || ".");
I don't like how it is a period. Replace it with something more obvious as to what it is.

2019-10-31 21:53 UTC, jacobgasser approved these changes

2019-10-31 21:54 UTC, merged