Created info command.
codesupport/old-discord-bot pull request #35
Opened 2019-11-23 21:11 UTC by Salint

2019-11-24 23:15 UTC, jacobgasser requested changes

2019-11-24 23:15 UTC, jacobgasser commented on commands/info.js
> +  .setField("Credits", "CodeSupport was founded in 2016 by LamboCreeper, also known as Lambo.")
Replace "LamboCreeper, also known as Lambo." with "<@136148682952146944>" so that it soft pings him.
(soft ping is where is shows up like a ping but it doesn't ping him)

2019-11-24 23:15 UTC, jacobgasser commented on commands/info.js
> +  .setField("About CodeSupport", "CodeSupport is a discord community with over 5,000 members\ndedicated to helping people in learning how to code.")
Replace "over 5,000" with number of members in server.

2019-11-24 23:15 UTC, jacobgasser commented on commands/info.js
> +  .setField("About CodeSupport", "CodeSupport is a discord community with over 5,000 members\ndedicated to helping people in learning how to code.")
"in learning" 
Replace with "to learn"

2019-11-25 07:42 UTC, LamboCreeper commented on commands/info.js
> +  .setField("About CodeSupport", "CodeSupport is a discord community with over 5,000 members\ndedicated to helping people in learning how to code.")
I’d rather the entire sentence was ”CodeSupport is a community dedicated to giving guidance about programming, as well as creating conversation with one another.” for consistency.

2019-11-25 07:46 UTC, LamboCreeper commented on commands/info.js
> +  .setField("Credits", "CodeSupport was founded in 2016 by LamboCreeper, also known as Lambo.")
It might be worth replacing this section with information about the team:
- @Lambo, Founder & Moderator
- @EKW, Moderator
- @Iffy, Mod Assistant
- @Sara, Mod Assistant

(soft ping everyone, see Jacob’s other comment)

2020-01-09 22:23 UTC, LamboCreeper commented
Nothing seems to be happening with this, going to close it.

2020-01-09 22:24 UTC, closed without merging