Adds contributing guidelines.
codesupport/old-discord-bot pull request #36
Opened 2019-11-23 21:13 UTC by LamboCreeper

Makes it more clear to people who wish to contribute to the project.

2019-11-24 23:08 UTC, jacobgasser requested changes

2019-11-24 23:08 UTC, jacobgasser commented on .github/contributing.md
> +If you are considering contributing please read through this document, if you have any questions do not hesitate to ask in the CodeSupport Discord.
"If you are considering contributing, please read through this document. If you have any questions please do not hesitate to ask in the <link somehow>CodeSupport Discord</link somehow>"

2019-11-24 23:08 UTC, jacobgasser commented on .github/contributing.md
> +5. Create a pull request, merging your branch back into the CodeSupport Discord Bot repository's develop branch.
Remove period

2019-11-24 23:08 UTC, jacobgasser commented on .github/contributing.md
> +
Add something about including your discord name

2019-11-27 07:18 UTC, LamboCreeper commented on .github/contributing.md
> +
Good point! This would be super handy.

2019-11-29 15:30 UTC, jacobgasser approved these changes

2019-11-29 15:34 UTC, jacobgasser approved these changes

2019-11-29 15:35 UTC, merged