Command Handler
codesupport/old-discord-bot pull request #4
Opened 2019-10-06 15:23 UTC by LamboCreeper

Creates a command handler to register commands for the bot. Any commands that have the property `visible` set to `true` will also appear in a command list.

An example command should have code like (you can use this as a template for building commands if you wish):
```js
// Set the command's properties
const properties = {
	command: "test",
	description: "This describes what the command does.",
	prefix: true,
	arguments: ["<required argument>", "[optional argument]"],
	visible: false,
	botchat: false
};

// The code that runs when the command is executed.
function run(message) {
	console.log(`${message.author.username} ran the command.`);
}

// Export the data to the command handler
exports.properties = properties
exports.run = run;
```

2019-10-06 15:27 UTC, Bas-Sarrechia requested changes
see inline comments.

2019-10-06 15:27 UTC, itsiffy commented on app.js
> +var commands = {};
Use let.

2019-10-06 15:27 UTC, itsiffy commented on app.js
> +const fs = require("fs");
what is 'fs'. Const are written in capital with underscores

2019-10-06 15:27 UTC, itsiffy commented on app.js
>  const config = require("./config.json");
Const are written in capital with underscores

2019-10-06 15:27 UTC, itsiffy commented on app.js
>  const client = new Discord.Client({
Const are written in capital with underscores

2019-10-06 15:27 UTC, itsiffy commented on app.js
> +		const args = message.content.split(" ");
Const are written in capital with underscores

2019-10-06 15:27 UTC, itsiffy commented on app.js
> +		const embed = new Discord.RichEmbed();
Const are written in capital with underscores

2019-10-06 15:27 UTC, itsiffy commented on app.js
> +			const properties = commands[commandFile].properties;
Const are written in capital with underscores

2019-10-06 15:27 UTC, itsiffy commented on app.js
> +
Const are written in capital with underscores

2019-10-06 15:29 UTC, LamboCreeper commented on app.js
> +const fs = require("fs");
It's Node.js's file I/O system, it is used for reading the commands directory as part of the command handler.

2019-10-06 15:37 UTC, itsiffy commented on app.js
> +const fs = require("fs");
Require a meaningful non abriviated but short name for this variable.

2019-10-06 15:45 UTC, Bas-Sarrechia approved these changes

2019-10-06 20:54 UTC, saramaebee commented
I still disagree with the usage of `fileSystem` instead of `fs`. I think this should be discussed more with everyone who would be working on the bot, and I won't approve it until a consensus is reached.

2019-10-06 20:58 UTC, Jason2605 commented on app.js
> +				}
Could this section not be shortened down to:
```js
const messagePrefix = properties.prefix ? config.prefix : properties.command;

if (message.content.startsWith(messagePrefix)) {
    if (properties.arguments.length === 0) {
        command.run(message);
    } else {
        command.run(message, args);
    }
}
```

2019-10-07 12:29 UTC, saramaebee approved these changes
Approving. Discussions regarding `fs` vs `fileSystem` needs to occur. If it is decided that we do not use `fs`, `fileSystem` should be changed to `filesystem`

2019-10-07 12:29 UTC, merged