Add basic standard logging mechanism
codesupport/old-discord-bot pull request #43
Opened 2019-12-09 22:12 UTC by AtrumAmantus

Add a basic logging mechanism to make logs look prettier and more useful.

2019-12-10 07:16 UTC, LamboCreeper requested changes

2019-12-10 07:16 UTC, LamboCreeper commented on utils/arrayUtils.js
> +function contains(array, object) {
This already exists in JavaScript as `Array.includes()`, see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes).

2019-12-10 07:16 UTC, LamboCreeper commented on utils/dateUtils.js
> +function DateFormat(date) {
A lot of this file should be a Class.

2019-12-10 07:16 UTC, LamboCreeper commented on utils/numberUtils.js
> +function isNumber(object) {
Is a function really needed for this?

2019-12-10 07:16 UTC, LamboCreeper commented on utils/stringUtils.js
> +function match(regex, object) {
Could you not use `.test()` here? See [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test).

2019-12-10 07:16 UTC, LamboCreeper commented on app.js
> +const Log = require("./logging/logging.js");
If a variable doesn't reference a Class it should be camelCase.

2019-12-10 11:40 UTC, AtrumAmantus commented on utils/arrayUtils.js
> +function contains(array, object) {
Ha, shows how much I do javascript, includes() by itself isn't null safe though.  If the object isn't an array it would throw an error, could change to return `return !isEmpty(array) && array.includes(0);`

2019-12-10 11:44 UTC, AtrumAmantus commented on utils/dateUtils.js
> +function DateFormat(date) {
probably, i didn't see any classes being used though

2019-12-10 11:45 UTC, AtrumAmantus commented on utils/numberUtils.js
> +function isNumber(object) {
it makes repeated use within the same file simple and more concise

2019-12-10 11:47 UTC, AtrumAmantus commented on utils/stringUtils.js
> +function match(regex, object) {
I'm unaware of a `test()` method for string, this would use `match()`, however `match()` returns null if no matches, so this adds a static `isMatch` which seems more intuitive than `object !== undefined`

2019-12-10 11:51 UTC, AtrumAmantus commented on app.js
> +const Log = require("./logging/logging.js");
it's sort of a class, at least as far as javascript treats classes, it's a collection of methods that perform related logic.  I'm not very versed in javascript's limited "class" features, but the implementation seems the same as with a class.

2019-12-10 12:35 UTC, LamboCreeper commented on utils/dateUtils.js
> +function DateFormat(date) {
Personally, anything that requires `new` before should be a class rather than a function.

2019-12-10 12:36 UTC, LamboCreeper commented on app.js
> +const Log = require("./logging/logging.js");
It just makes more sense readability wise that they're all related rather than lots of functions in a file.

2019-12-10 12:38 UTC, AtrumAmantus commented on utils/dateUtils.js
> +function DateFormat(date) {
Class is just syntactical sugar though isn't it? It doesn't actually do anything different from my understanding.  I suppose it makes it more intuitive when you are reading the code though

2019-12-10 13:41 UTC, AtrumAmantus commented on utils/dateUtils.js
> +function DateFormat(date) {
This has been updated

2019-12-10 16:27 UTC, AtrumAmantus commented on app.js
> +const Log = require("./logging/logging.js");
Created sort of a pseudo class, not sure if there is a better way, was the only way I could keep the private methods private.

2019-12-10 16:54 UTC, LamboCreeper reviewed
Might be worth taking a look at [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), it can help save lines of code.

2019-12-10 16:54 UTC, LamboCreeper commented on utils/dateUtils.js
> +const padString = StringUtils.padString;
You could just do `const {padString} = require("./stringUtils.js");`

2019-12-10 16:54 UTC, LamboCreeper commented on utils/stringUtils.js
> +const isNumber = NumberUtils.isNumber;
Same here: `const {isNumber} = require("./numberUtils.js");`

2019-12-10 17:01 UTC, AtrumAmantus commented on utils/dateUtils.js
> +const padString = StringUtils.padString;
fixed

2019-12-10 17:01 UTC, AtrumAmantus commented on utils/stringUtils.js
> +const isNumber = NumberUtils.isNumber;
fixed

2019-12-15 17:28 UTC, LamboCreeper approved these changes

2019-12-15 17:28 UTC, merged