Feature/bot optimizations
codesupport/old-discord-bot pull request #46
Opened 2019-12-15 23:53 UTC by AtrumAmantus

Add .editorconfig for convenience
Remove package-lock.json (generated file)
Add package-lock.json to .gitignore
Add root directory reference as global variable
Update all directory paths to use root directory global variable
Simplify command/event loading/invocation
Add commands command for getting commands
Add needed utilities

2019-12-17 07:47 UTC, LamboCreeper requested changes
Not really sure what this pull request achieves apart from over-complicating everything, making it harder for people to contribute?

2019-12-17 07:47 UTC, LamboCreeper commented on .editorconfig
> +root = true
This should not be in the repository. Add any editor configurations to the `.gitignore`.

2019-12-17 07:47 UTC, LamboCreeper commented on .gitignore
> +package-lock.json
The `package-lock.json` should be in the repository for working out dependencies. Please add this back.

2019-12-17 07:47 UTC, LamboCreeper commented on app.js
> +global._ROOT_DIR = path.resolve(__dirname);
I really don't understand the point of this, it overcomplicates the basic paths we had before.

2019-12-17 07:47 UTC, LamboCreeper commented on app/Commands.js
> +const Commands = (() => {
Please use a class and export a new instance of itself.

2019-12-17 07:47 UTC, LamboCreeper commented on app/Events.js
> +const Events = (() => {
Same here.

2019-12-17 07:47 UTC, LamboCreeper commented on app/appLoader.js
> +const AppLoader = (() => {
and here.

2019-12-17 11:54 UTC, AtrumAmantus commented on .editorconfig
> +root = true
.editorconfig is a cross IDE configuration to help enforce standards, i.e. how to format tabs, line endings, etc.  If the IDE you use supports it (which there are many that do) it will be of help, if not, it does nothing.

2019-12-17 11:55 UTC, AtrumAmantus commented on .gitignore
> +package-lock.json
package-lock.json is a generated file, when you do npm install it creates it.  Generated files shouldn't be in the repo.

2019-12-17 11:58 UTC, AtrumAmantus commented on app.js
> +global._ROOT_DIR = path.resolve(__dirname);
before there were paths like `const val = require("../helper/date.js")` navigating up and down trees is confusing, and if you move the dep it breaks.  If you do an absolute path `const val = require("${_ROOT_DIR}/helper/date.js")` you can move the file with the require anywhere and it still works.  As it is, the flat structure of the project is a bit disorganized, most node projects I've seen have all their folders in a src folder, so then you will have paths like `const app = require ("../../app.js")` instead of `const app = ("${_ROOT_DIR}/app.js)` which i would say is less desirable

2019-12-17 11:58 UTC, AtrumAmantus commented on app/Commands.js
> +const Commands = (() => {
Classes do not allow the ability to have private methods, this is the only way i've found to do private methods

2019-12-17 11:59 UTC, AtrumAmantus commented on app/Events.js
> +const Events = (() => {
same here.

2019-12-17 11:59 UTC, AtrumAmantus commented on app/appLoader.js
> +const AppLoader = (() => {
And here

2019-12-17 12:03 UTC, AtrumAmantus reviewed
Clean code and good OOP practices are not more complex, they are more maintainable.  One example, why was there procedural code for the `?commands` command?  It's just a command like any other, so this PR made it one.  Commands/Events were also loaded procedurally, in a duplicate fashion.  The App.jar shouldn't care how those commands are loaded, only that they are, that is SoC (Separation of Concerns), a key aspect of design, and the way they are loaded is exactly the same, so it should be a separate utility.  None of this prohibits anyone in any way from contributing, it instead encourages clean maintainable code.

2019-12-17 12:23 UTC, LamboCreeper commented on .gitignore
> +package-lock.json
See [here](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5).

2019-12-17 12:24 UTC, LamboCreeper commented on app.js
> +global._ROOT_DIR = path.resolve(__dirname);
Okay, I get your points.

2019-12-17 12:46 UTC, AtrumAmantus commented on app.js
> -
This was an accidental commit from my local setup, ignore this, it was removed

2019-12-17 12:47 UTC, AtrumAmantus commented on .gitignore
> +package-lock.json
understood, added package-lock.json back and removed from .gitignore

2019-12-20 13:48 UTC, LamboCreeper approved these changes

2019-12-20 13:48 UTC, merged