Edited message update event handler so links don't get sent to logs
codesupport/old-discord-bot pull request #50
Opened 2020-01-02 23:26 UTC by jacobgasser

### What does this change/add/remove?
Added condition to see if the old message was the same as the new message in the message update event.

### Why is this beneficial to the project?
Now links will not be sent to #logs whenever the metadata for the page is received and Discord adds an embed to the message.

2020-01-02 23:28 UTC, LamboCreeper requested changes
The logic should live in the event, not the app.

2020-01-02 23:59 UTC, AtrumAmantus requested changes

2020-01-02 23:59 UTC, AtrumAmantus commented on events/messageUpdate.js
> +	}
Happy path first, no fast fails
```
if (oldMessage.content != newMessage.content) {
    //...
}```

2020-01-03 00:01 UTC, jacobgasser commented on events/messageUpdate.js
> +	}
okie dokie

2020-01-03 00:08 UTC, jacobgasser commented on events/messageUpdate.js
> +	}
can I ask why?

2020-01-03 00:15 UTC, AtrumAmantus commented on events/messageUpdate.js
> +	}
You should only ever have one return, and it should be at the end of the function for readability.  Using fast fails is a code smell for duct tape programming.  Not nesting your conditionals lowers the ability to codesmell for overcomplexity.

2020-01-03 15:16 UTC, LamboCreeper approved these changes

2020-01-07 03:30 UTC, AtrumAmantus approved these changes

2020-01-07 03:30 UTC, merged