Command handler cleanup
codesupport/old-discord-bot pull request #6
Opened 2019-10-08 00:01 UTC by saramaebee

2019-10-08 06:07 UTC, itsiffy commented on app.js
> +const filesystem = require("fs");
fileSystem was correct -> camelcasing. file + system (two different words)

2019-10-08 06:32 UTC, Bas-Sarrechia requested changes
preferable integrate tests with jester to confirm logic works.
See inline comments on todo.

2019-10-08 06:32 UTC, itsiffy commented on app.js
> +		}
this part can likely be written better and is likely flawed in logic. try to reconsider this continue; statement

2019-10-08 06:32 UTC, itsiffy commented on app.js
> +			}
again see above comment.
-> reason potential breaking in future
-> excess of logic = loss in performance

2019-10-08 15:17 UTC, LamboCreeper commented on app.js
> +		}
I'd rather `continue;` wasn't used.

2019-10-13 12:18 UTC, LamboCreeper commented
Closed for reasons discussed within Discord.

2019-10-13 12:18 UTC, closed without merging